import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Migration 1775047395773 - AddDetailsJsonbAndPopulateOffers
 *
 * 1. Aggiunge colonna `details` JSONB alla tabella `offers`.
 * 2. Elimina e re-inserisce le offerte ENERGY con dati strutturati reali (60 offerte).
 * 3. Inserisce le offerte MOBILE con dati strutturati reali (38 offerte, idempotente).
 *
 * Rollback: elimina tutte le offerte ENERGY e MOBILE dei provider importati.
 */
export class AddDetailsJsonbAndPopulateOffers1775047395773 implements MigrationInterface {
  name = 'AddDetailsJsonbAndPopulateOffers1775047395773';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // === 1. Aggiungi colonna details JSONB ===
    await queryRunner.query(`ALTER TABLE offers ADD COLUMN IF NOT EXISTS details JSONB`);

    // === 2. Pulisci offerte ENERGY vecchie (dalla migration precedente) ===
    await queryRunner.query(
      `DELETE FROM offers WHERE category = 'ENERGY' AND provider IN ('OPTIMA','IREN','ITALIA POWER','WINDTRE','ACEA','FASTWEB','A2A')`
    );

    // === 3. Inserisci offerte ENERGY con details ===
    const energyOffers = [
      { provider: 'OPTIMA', name: 'SUPER CASA SMART LUCE', canone: '0,22', vincolo: '', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "FISSO", "f1": "0,22", "f2": "", "f3": "", "pcv": "12", "durata": "", "scadenza_offerta": "", "pagamento": "RID", "cauzione": "", "fatturazione": "", "switch_voltura": "SI", "subentro": "NO", "note_raw": ""}' },
      { provider: 'OPTIMA', name: 'SUER CASA SMART LUCE', canone: '60% VARIABILE PUN +0,044(INCLUSE PERDITE DI RETE) 40% FISSA 0,195 KWH', vincolo: '12 MESI POI PASSA A VARIABILE', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "MISTA", "f1": "60% VARIABILE PUN +0,044(INCLUSE PERDITE DI RETE) 40% FISSA 0,195 KWH", "f2": "", "f3": "", "pcv": "9", "durata": "12 MESI POI PASSA A VARIABILE", "scadenza_offerta": "", "pagamento": "RID", "cauzione": "", "fatturazione": "", "switch_voltura": "SI", "subentro": "NO", "note_raw": ""}' },
      { provider: 'OPTIMA', name: 'SUPER CASA SMART LUCE', canone: 'PUN + 0,080', vincolo: 'NESSUNA SCAD.', scadenza: '', type: 'consumer', note: 'NO', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "VARIABILE", "f1": "PUN + 0,080", "f2": "", "f3": "", "pcv": "9", "durata": "NESSUNA SCAD.", "scadenza_offerta": "", "pagamento": "", "cauzione": "RID", "fatturazione": "20€ PER KW", "switch_voltura": "MENSILE", "subentro": "SI", "note_raw": "NO"}' },
      { provider: 'OPTIMA', name: 'SUPER CASA SMART GAS', canone: 'PSV + 0,200', vincolo: 'NESSUNA SCAD.', scadenza: '', type: 'consumer', note: 'SI', details: '{"fornitura": "GAS", "tipologia": "CONSUMER", "tipo_offerta": "VARIABILE", "f1": "PSV + 0,200", "f2": "", "f3": "", "pcv": "8,9", "durata": "NESSUNA SCAD.", "scadenza_offerta": "", "pagamento": "", "cauzione": "RID", "fatturazione": "", "switch_voltura": "MENSILE", "subentro": "NO", "note_raw": "SI"}' },
      { provider: 'OPTIMA', name: 'SUPER IMPRESA SMART LUCE', canone: 'PUN + 0,02', vincolo: 'NESSUNA SCAD.', scadenza: '', type: 'business', note: 'SI', details: '{"fornitura": "LUCE", "tipologia": "BUSINESS", "tipo_offerta": "VARIABILE", "f1": "PUN + 0,02", "f2": "", "f3": "", "pcv": "17,5", "durata": "NESSUNA SCAD.", "scadenza_offerta": "", "pagamento": "", "cauzione": "RID", "fatturazione": "", "switch_voltura": "MENSILE", "subentro": "NO", "note_raw": "SI"}' },
      { provider: 'OPTIMA', name: 'SUPER IMPRESA SMART GAS', canone: 'PSV + 0,15', vincolo: 'NESSUNA SCAD.', scadenza: '', type: 'business', note: 'SI', details: '{"fornitura": "GAS", "tipologia": "BUSINESS", "tipo_offerta": "VARIABILE", "f1": "PSV + 0,15", "f2": "", "f3": "", "pcv": "20", "durata": "NESSUNA SCAD.", "scadenza_offerta": "", "pagamento": "", "cauzione": "RID", "fatturazione": "", "switch_voltura": "MENSILE", "subentro": "NO", "note_raw": "SI"}' },
      { provider: 'IREN', name: 'IREN SOTTO CASA LUCE', canone: '0,116', vincolo: '12 MESI', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "FISSO", "f1": "0,116", "f2": "", "f3": "", "pcv": "13,25", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "NO", "fatturazione": "BIMESTRALE", "switch_voltura": "SI", "subentro": "NO", "note_raw": ""}' },
      { provider: 'IREN', name: 'IREN SOTTO CASA GAS', canone: '0,45', vincolo: '12 MESI', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "GAS", "tipologia": "CONSUMER", "tipo_offerta": "FISSO", "f1": "0,45", "f2": "", "f3": "", "pcv": "13", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "NO", "fatturazione": "BIMESTRALE", "switch_voltura": "NO", "subentro": "NO", "note_raw": ""}' },
      { provider: 'IREN', name: 'SEV IREN QUICK LUCE', canone: '0,135 (INCLUSE PERDITE DI RETE)', vincolo: '12 MESI', scadenza: '20 marzo', type: 'consumer', note: '', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "FISSO", "f1": "0,135 (INCLUSE PERDITE DI RETE)", "f2": "", "f3": "", "pcv": "11,25", "durata": "12 MESI", "scadenza_offerta": "20 marzo", "pagamento": "RID/BOLLETTINO", "cauzione": "NO", "fatturazione": "", "switch_voltura": "", "subentro": "", "note_raw": ""}' },
      { provider: 'IREN', name: 'SEV IREN QUICK GAS', canone: '0,57', vincolo: '12 MESI', scadenza: '20 marzo', type: 'consumer', note: '', details: '{"fornitura": "GAS", "tipologia": "CONSUMER", "tipo_offerta": "FISSO", "f1": "0,57", "f2": "", "f3": "", "pcv": "11", "durata": "12 MESI", "scadenza_offerta": "20 marzo", "pagamento": "RID/BOLLETTINO", "cauzione": "NO", "fatturazione": "", "switch_voltura": "", "subentro": "", "note_raw": ""}' },
      { provider: 'IREN', name: 'IREN TUA AZIENDA  LUCE', canone: '0,172', vincolo: '', scadenza: '', type: 'business', note: '', details: '{"fornitura": "LUCE", "tipologia": "BUSINESS", "tipo_offerta": "FISSO", "f1": "0,172", "f2": "", "f3": "", "pcv": "15", "durata": "", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "", "switch_voltura": "SI", "subentro": "NO", "note_raw": ""}' },
      { provider: 'IREN', name: 'IREN TUA AZIENDA GAS', canone: '0,688', vincolo: '', scadenza: '', type: 'business', note: '', details: '{"fornitura": "GAS", "tipologia": "BUSINESS", "tipo_offerta": "FISSO", "f1": "0,688", "f2": "", "f3": "", "pcv": "15", "durata": "", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "", "switch_voltura": "", "subentro": "", "note_raw": ""}' },
      { provider: 'IREN', name: 'SEV BONUS 60 LUCE GREEN', canone: 'PUN + 0,015', vincolo: '12 MESI', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "VARIABILE", "f1": "PUN + 0,015", "f2": "", "f3": "", "pcv": "7", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "NO", "fatturazione": "BIMESTRALE", "switch_voltura": "SI", "subentro": "SI", "note_raw": ""}' },
      { provider: 'IREN', name: 'SEV BONUS 60 GAS GREEN', canone: 'PSV + 0,15', vincolo: '12 MESI', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "GAS", "tipologia": "CONSUMER", "tipo_offerta": "VARIABILE", "f1": "PSV + 0,15", "f2": "", "f3": "", "pcv": "7", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "NO", "fatturazione": "", "switch_voltura": "SI", "subentro": "SI", "note_raw": ""}' },
      { provider: 'IREN', name: 'SEV FULL ENERGY LUCE SPECIAL EDITION', canone: '0,15', vincolo: '12 MESI', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "FISSO", "f1": "0,15", "f2": "", "f3": "", "pcv": "11,5", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "NO", "fatturazione": "BIMESTRALE", "switch_voltura": "SI", "subentro": "SI", "note_raw": ""}' },
      { provider: 'IREN', name: 'SEV FULL ENERGY GAS SPECIAL EDITION', canone: '0,61', vincolo: '12 MESI', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "GAS", "tipologia": "CONSUMER", "tipo_offerta": "FISSO", "f1": "0,61", "f2": "", "f3": "", "pcv": "11,5", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "NO", "fatturazione": "BIMESTRALE", "switch_voltura": "SI", "subentro": "SI", "note_raw": ""}' },
      { provider: 'IREN', name: 'SEV FULL ENERGY LUCE (CONV FIBRA)', canone: 'PUN + 0,045', vincolo: 'NESSUNA SCAD.', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "VARIABILE", "f1": "PUN + 0,045", "f2": "", "f3": "", "pcv": "12", "durata": "NESSUNA SCAD.", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "NO", "fatturazione": "BIMESTRALE", "switch_voltura": "SI", "subentro": "SI", "note_raw": ""}' },
      { provider: 'IREN', name: 'SEV FULL ENERGY GAS (CONV FIBRA)', canone: 'PSV + 0,20', vincolo: 'NESSUNA SCAD.', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "GAS", "tipologia": "CONSUMER", "tipo_offerta": "VARIABILE", "f1": "PSV + 0,20", "f2": "", "f3": "", "pcv": "12", "durata": "NESSUNA SCAD.", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "NO", "fatturazione": "BIMESTRALE", "switch_voltura": "SI", "subentro": "SI", "note_raw": ""}' },
      { provider: 'ITALIA POWER', name: 'MONETITO FIX', canone: '0,139', vincolo: '12 MESI', scadenza: '31/03', type: 'consumer', note: '', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "FISSO", "f1": "0,139", "f2": "", "f3": "", "pcv": "13,5", "durata": "12 MESI", "scadenza_offerta": "31/03", "pagamento": "", "cauzione": "", "fatturazione": "", "switch_voltura": "", "subentro": "", "note_raw": ""}' },
      { provider: 'ITALIA POWER', name: 'MONETITO FIX', canone: '0,49', vincolo: '12 MESI', scadenza: '31/03', type: 'consumer', note: '', details: '{"fornitura": "GAS", "tipologia": "CONSUMER", "tipo_offerta": "FISSO", "f1": "0,49", "f2": "", "f3": "", "pcv": "11,9", "durata": "12 MESI", "scadenza_offerta": "31/03", "pagamento": "", "cauzione": "", "fatturazione": "", "switch_voltura": "", "subentro": "", "note_raw": ""}' },
      { provider: 'ITALIA POWER', name: 'PUN ZERO', canone: 'PUN + 0', vincolo: 'NESSUNA SCAD.', scadenza: 'DA OGGI SE IL CLIENTE ATTIVA DUAL LUCE E GAS HA DIRITTO ALL\'ASSICURAZIONE RC CASA INCLUSA', type: 'consumer', note: '', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "VARIABILE", "f1": "PUN + 0", "f2": "", "f3": "", "pcv": "13,5", "durata": "NESSUNA SCAD.", "scadenza_offerta": "DA OGGI SE IL CLIENTE ATTIVA DUAL LUCE E GAS HA DIRITTO ALL\'ASSICURAZIONE RC CASA INCLUSA", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "MENSILE/BIMESTRALE", "switch_voltura": "SI", "subentro": "", "note_raw": ""}' },
      { provider: 'ITALIA POWER', name: '"PSV Day Ahead (DA) + 0,09"', canone: 'PSV + 0,09', vincolo: 'NESSUNA SCAD.', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "GAS", "tipologia": "CONSUMER", "tipo_offerta": "VARIABILE", "f1": "PSV + 0,09", "f2": "", "f3": "", "pcv": "12,9", "durata": "NESSUNA SCAD.", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "", "switch_voltura": "SI", "subentro": "", "note_raw": ""}' },
      { provider: 'ITALIA POWER', name: 'SUMMER LUCE', canone: 'PUN + 0,019', vincolo: 'NESSUNA SCAD.', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "VARIABILE", "f1": "PUN + 0,019", "f2": "", "f3": "", "pcv": "9,5", "durata": "NESSUNA SCAD.", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "", "switch_voltura": "SI", "subentro": "", "note_raw": ""}' },
      { provider: 'ITALIA POWER', name: 'MONETITO ALTRI USI MONO (SCALE/GARAGE CON CF.)', canone: 'PUN+ 0,019', vincolo: 'NESSUNA SCAD.', scadenza: '', type: 'business', note: '', details: '{"fornitura": "LUCE", "tipologia": "BUSINESS", "tipo_offerta": "VARIABILE", "f1": "PUN+ 0,019", "f2": "", "f3": "", "pcv": "13,5", "durata": "NESSUNA SCAD.", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "", "switch_voltura": "", "subentro": "", "note_raw": ""}' },
      { provider: 'ITALIA POWER', name: 'SMART BUSINESS LUCE', canone: 'PUN+0,019', vincolo: 'NESSUNA SCAD.', scadenza: '', type: 'business', note: '', details: '{"fornitura": "LUCE", "tipologia": "BUSINESS", "tipo_offerta": "VARIABILE", "f1": "PUN+0,019", "f2": "", "f3": "", "pcv": "12,9", "durata": "NESSUNA SCAD.", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "", "switch_voltura": "NO", "subentro": "", "note_raw": ""}' },
      { provider: 'ITALIA POWER', name: 'PSV 19 BUSINESS', canone: 'PSV+0,09', vincolo: '', scadenza: '', type: 'business', note: '', details: '{"fornitura": "GAS", "tipologia": "BUSINESS", "tipo_offerta": "VARIABILE", "f1": "PSV+0,09", "f2": "", "f3": "", "pcv": "24,9", "durata": "", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "", "switch_voltura": "", "subentro": "", "note_raw": ""}' },
      { provider: 'WINDTRE', name: 'NEW START CASA', canone: 'PUN+0,027', vincolo: '24 MESI', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "VARIABILE", "f1": "PUN+0,027", "f2": "", "f3": "", "pcv": "7,50 (CLT W3)/13", "durata": "24 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "SI BP", "fatturazione": "MENSILE", "switch_voltura": "SI", "subentro": "NO", "note_raw": ""}' },
      { provider: 'WINDTRE', name: 'NEW START CASA', canone: 'PSV+0,09', vincolo: '24 MESI', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "GAS", "tipologia": "CONSUMER", "tipo_offerta": "VARIABILE", "f1": "PSV+0,09", "f2": "", "f3": "", "pcv": "7,50 (CLT W3)/13", "durata": "24 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "SI  BP", "fatturazione": "MENSILE", "switch_voltura": "SI", "subentro": "NO", "note_raw": ""}' },
      { provider: 'WINDTRE', name: 'NEW START PRO', canone: 'PUN+0,027', vincolo: '24 MESI', scadenza: '', type: 'business', note: '', details: '{"fornitura": "LUCE", "tipologia": "BUSINESS", "tipo_offerta": "VARIABILE", "f1": "PUN+0,027", "f2": "", "f3": "", "pcv": "9,50 (CLT W3)/17,50", "durata": "24 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "SI  BP", "fatturazione": "MENSILE", "switch_voltura": "SI", "subentro": "NO", "note_raw": ""}' },
      { provider: 'WINDTRE', name: 'NEW START PRO', canone: 'PSV+0,09', vincolo: '24 MESI', scadenza: '', type: 'business', note: '', details: '{"fornitura": "GAS", "tipologia": "BUSINESS", "tipo_offerta": "VARIABILE", "f1": "PSV+0,09", "f2": "", "f3": "", "pcv": "9,50 (CLT W3)/17,50", "durata": "24 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "SI BP", "fatturazione": "MENSILE", "switch_voltura": "SI", "subentro": "NO", "note_raw": ""}' },
      { provider: 'WINDTRE', name: 'FLEX', canone: 'PUN+ 0,025', vincolo: '24 MESI', scadenza: '', type: 'consumer', note: 'RID ANCHE INTESTATARIO DIFFERENTE', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "VARIABILE", "f1": "PUN+ 0,025", "f2": "", "f3": "", "pcv": "8 (CLT) /13", "durata": "24 MESI", "scadenza_offerta": "", "pagamento": "RID", "cauzione": "", "fatturazione": "MENSILE", "switch_voltura": "SI", "subentro": "SI", "note_raw": "RID ANCHE INTESTATARIO DIFFERENTE"}' },
      { provider: 'WINDTRE', name: 'BUSINESS FLEX', canone: 'PUN+ 0,037', vincolo: '24 MESI', scadenza: '', type: 'business', note: 'RID ANCHEINTESTATARIO DIFFERENTE', details: '{"fornitura": "LUCE", "tipologia": "BUSINESS", "tipo_offerta": "VARIABILE", "f1": "PUN+ 0,037", "f2": "", "f3": "", "pcv": "5 (CLT) /20", "durata": "24 MESI", "scadenza_offerta": "", "pagamento": "RID", "cauzione": "", "fatturazione": "MENSILE", "switch_voltura": "SI", "subentro": "SI", "note_raw": "RID ANCHEINTESTATARIO DIFFERENTE"}' },
      { provider: 'ACEA', name: 'ACEA FIX', canone: '0,181', vincolo: '12 MESI', scadenza: '', type: 'consumer', note: 'RID ANCHE CON INTESTATARIO DIFFERENTE', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "FISSO", "f1": "0,181", "f2": "", "f3": "", "pcv": "12", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "NO", "fatturazione": "MENSILE", "switch_voltura": "SI", "subentro": "NO", "note_raw": "RID ANCHE CON INTESTATARIO DIFFERENTE"}' },
      { provider: 'ACEA', name: 'ACEA FIX', canone: 'FISSO 0,66', vincolo: '12 MESI', scadenza: '', type: 'consumer', note: 'RID ANCHE CON INTESTATARIO DIFFERENTE', details: '{"fornitura": "GAS", "tipologia": "CONSUMER", "tipo_offerta": "FISSO", "f1": "FISSO 0,66", "f2": "", "f3": "", "pcv": "12", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "MENSILE", "switch_voltura": "SI", "subentro": "SI", "note_raw": "RID ANCHE CON INTESTATARIO DIFFERENTE"}' },
      { provider: 'ACEA', name: 'ACEA SPRINT LUCE', canone: 'PUN+0,142', vincolo: '12 MESI', scadenza: '', type: 'consumer', note: 'RID ANCHE CON INTESTATARIO DIFFERENTE', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "VARIABILE", "f1": "PUN+0,142", "f2": "", "f3": "", "pcv": "10", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "MENSILE", "switch_voltura": "SI", "subentro": "SI", "note_raw": "RID ANCHE CON INTESTATARIO DIFFERENTE"}' },
      { provider: 'ACEA', name: 'ACEA SPRINT GAS', canone: 'PSV+ 0,053', vincolo: '12 MESI', scadenza: '', type: 'consumer', note: 'RID ANCHE CON INTESTATARIO DIFFERENTE', details: '{"fornitura": "GAS", "tipologia": "CONSUMER", "tipo_offerta": "VARIABILE", "f1": "PSV+ 0,053", "f2": "", "f3": "", "pcv": "10", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "MENSILE", "switch_voltura": "SI", "subentro": "SI", "note_raw": "RID ANCHE CON INTESTATARIO DIFFERENTE"}' },
      { provider: 'ACEA', name: 'ACEA FLEX', canone: 'PUN+ 0,03', vincolo: '12 MESI', scadenza: '', type: 'consumer', note: 'RID ANCHE CON INTESTATARIO DIFFERENTE', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "VARIABILE", "f1": "PUN+ 0,03", "f2": "", "f3": "", "pcv": "9", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "MENSILE", "switch_voltura": "SI", "subentro": "SI", "note_raw": "RID ANCHE CON INTESTATARIO DIFFERENTE"}' },
      { provider: 'ACEA', name: 'ACEA FLEX', canone: 'PSV+ 0,122', vincolo: '12 MESI', scadenza: '', type: 'consumer', note: 'RID ANCHE CON INTESTATARIO DIFFERENTE', details: '{"fornitura": "GAS", "tipologia": "CONSUMER", "tipo_offerta": "VARIABILE", "f1": "PSV+ 0,122", "f2": "", "f3": "", "pcv": "9", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "MENSILE", "switch_voltura": "SI", "subentro": "SI", "note_raw": "RID ANCHE CON INTESTATARIO DIFFERENTE"}' },
      { provider: 'ACEA', name: 'ACEA SPRINT BUSINESS', canone: 'PUN+  0,016', vincolo: '12 MESI', scadenza: '', type: 'business', note: 'RID ANCHE CON INTESTATARIO DIFFERENTE', details: '{"fornitura": "LUCE", "tipologia": "BUSINESS", "tipo_offerta": "VARIABILE", "f1": "PUN+  0,016", "f2": "", "f3": "", "pcv": "13", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "MENSILE", "switch_voltura": "SI", "subentro": "SI", "note_raw": "RID ANCHE CON INTESTATARIO DIFFERENTE"}' },
      { provider: 'ACEA', name: 'ACEA SPRINT BUSINESS', canone: 'PSV+ 0,056', vincolo: '12 MESI', scadenza: '', type: 'business', note: 'RID ANCHE CON INTESTATARIO DIFFERENTE', details: '{"fornitura": "GAS", "tipologia": "BUSINESS", "tipo_offerta": "VARIABILE", "f1": "PSV+ 0,056", "f2": "", "f3": "", "pcv": "13", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "MENSILE", "switch_voltura": "SI", "subentro": "SI", "note_raw": "RID ANCHE CON INTESTATARIO DIFFERENTE"}' },
      { provider: 'ACEA', name: 'START (5 ANNI)', canone: 'FINO A 800 KWH', vincolo: '5 ANNI', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "", "f1": "FINO A 800 KWH", "f2": "", "f3": "", "pcv": "30", "durata": "5 ANNI", "scadenza_offerta": "", "pagamento": "", "cauzione": "", "fatturazione": "", "switch_voltura": "", "subentro": "", "note_raw": ""}' },
      { provider: 'ACEA', name: 'LIGHT (5 ANNI)', canone: 'FINO A 1500 KWH', vincolo: '5 ANNI', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "", "f1": "FINO A 1500 KWH", "f2": "", "f3": "", "pcv": "45", "durata": "5 ANNI", "scadenza_offerta": "", "pagamento": "", "cauzione": "", "fatturazione": "", "switch_voltura": "", "subentro": "", "note_raw": ""}' },
      { provider: 'ACEA', name: 'PRO', canone: 'FINO A 2500 KWH', vincolo: '5 ANNI', scadenza: '', type: 'consumer', note: 'RID ANCHE CON INTESTATARIO DIFFERENTE', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "", "f1": "FINO A 2500 KWH", "f2": "", "f3": "", "pcv": "65", "durata": "5 ANNI", "scadenza_offerta": "", "pagamento": "RID", "cauzione": "", "fatturazione": "MENSILE", "switch_voltura": "NO", "subentro": "NO", "note_raw": "RID ANCHE CON INTESTATARIO DIFFERENTE"}' },
      { provider: 'ACEA', name: 'MAXI', canone: 'FINO A 3500 KWH', vincolo: '5 ANNI', scadenza: '', type: 'consumer', note: 'RID ANCHE CON INTESTATARIO DIFFERENTE', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "", "f1": "FINO A 3500 KWH", "f2": "", "f3": "", "pcv": "80", "durata": "5 ANNI", "scadenza_offerta": "", "pagamento": "RID", "cauzione": "", "fatturazione": "MENSILE", "switch_voltura": "NO", "subentro": "NO", "note_raw": "RID ANCHE CON INTESTATARIO DIFFERENTE"}' },
      { provider: 'FASTWEB', name: 'ULTRA', canone: 'FINO A 4500 KWH', vincolo: '5 ANNI', scadenza: '', type: 'consumer', note: 'RID ANCHE CON INTESTATARIO DIFFERENTE', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "", "f1": "FINO A 4500 KWH", "f2": "", "f3": "", "pcv": "95", "durata": "5 ANNI", "scadenza_offerta": "", "pagamento": "RID", "cauzione": "", "fatturazione": "MENSILE", "switch_voltura": "NO", "subentro": "NO", "note_raw": "RID ANCHE CON INTESTATARIO DIFFERENTE"}' },
      { provider: 'FASTWEB', name: 'FIX', canone: '0,18', vincolo: '12 MESI', scadenza: '', type: 'consumer', note: 'RID ANCHE CON INTESTATARIO DIFFERENTE', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "FISSO", "f1": "0,18", "f2": "", "f3": "", "pcv": "8/13", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID", "cauzione": "", "fatturazione": "MENSILE", "switch_voltura": "NO", "subentro": "NO", "note_raw": "RID ANCHE CON INTESTATARIO DIFFERENTE"}' },
      { provider: 'FASTWEB', name: 'FLEX', canone: 'PUN+0,026', vincolo: '12MESI', scadenza: '', type: 'consumer', note: 'RID ANCHE CON INTESTATARIO DIFFERENTE', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "VARIABILE", "f1": "PUN+0,026", "f2": "", "f3": "", "pcv": "8/13", "durata": "12MESI", "scadenza_offerta": "", "pagamento": "RID", "cauzione": "", "fatturazione": "MENSILE", "switch_voltura": "SI", "subentro": "SI", "note_raw": "RID ANCHE CON INTESTATARIO DIFFERENTE"}' },
      { provider: 'FASTWEB', name: 'FIX', canone: '0,16', vincolo: '12 MESI', scadenza: '', type: 'business', note: 'RID ANCHE CON INTESTATARIO DIFFERENTE', details: '{"fornitura": "LUCE", "tipologia": "BUSINESS", "tipo_offerta": "FISSO", "f1": "0,16", "f2": "", "f3": "", "pcv": "10/20", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID", "cauzione": "", "fatturazione": "MENSILE", "switch_voltura": "NO", "subentro": "NO", "note_raw": "RID ANCHE CON INTESTATARIO DIFFERENTE"}' },
      { provider: 'FASTWEB', name: 'FLEX', canone: 'PUN+0,030', vincolo: '12 MESI', scadenza: '', type: 'business', note: 'RID ANCHE CON INTESTATARIO DIFFERENTE', details: '{"fornitura": "LUCE", "tipologia": "BUSINESS", "tipo_offerta": "VARIABILE", "f1": "PUN+0,030", "f2": "", "f3": "", "pcv": "10/20", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID", "cauzione": "", "fatturazione": "MENSILE", "switch_voltura": "SI", "subentro": "SI", "note_raw": "RID ANCHE CON INTESTATARIO DIFFERENTE"}' },
      { provider: 'A2A', name: 'SMART CASA', canone: 'PUN+ 0,025', vincolo: '12 MESI', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "", "f1": "PUN+ 0,025", "f2": "", "f3": "", "pcv": "9,5", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "€5,20 PER KW", "fatturazione": "BIMESTRALE", "switch_voltura": "SI", "subentro": "SI", "note_raw": ""}' },
      { provider: 'A2A', name: 'ESCLUSIVA 2 A', canone: 'FISSO 0,139', vincolo: '12 MESI', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "", "f1": "FISSO 0,139", "f2": "", "f3": "", "pcv": "9,5", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "€5,20 PER KW", "fatturazione": "BIMESTRALE", "switch_voltura": "NO", "subentro": "NO", "note_raw": ""}' },
      { provider: 'A2A', name: 'A2A START', canone: 'FISSO 0,134', vincolo: '12 MESI', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "", "f1": "FISSO 0,134", "f2": "", "f3": "", "pcv": "9,5", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "€5,20 PER KW", "fatturazione": "BIMESTRALE", "switch_voltura": "SI", "subentro": "SI", "note_raw": ""}' },
      { provider: 'A2A', name: 'SMART CASA', canone: 'PSV+0,12', vincolo: '12 MESI', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "GAS", "tipologia": "CONSUMER", "tipo_offerta": "", "f1": "PSV+0,12", "f2": "", "f3": "", "pcv": "9,5", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "€5,20 PER KW", "fatturazione": "BIMESTRALE", "switch_voltura": "NO", "subentro": "NO", "note_raw": ""}' },
      { provider: 'A2A', name: 'ESCLUSIVA A2A', canone: 'FISSO 0,44', vincolo: '12 MESI', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "GAS", "tipologia": "CONSUMER", "tipo_offerta": "", "f1": "FISSO 0,44", "f2": "", "f3": "", "pcv": "9,5", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "BIMESTRALE", "switch_voltura": "SI", "subentro": "", "note_raw": ""}' },
      { provider: 'A2A', name: 'A2A START', canone: 'FISSO 0,40', vincolo: '24 MESI', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "GAS", "tipologia": "CONSUMER", "tipo_offerta": "", "f1": "FISSO 0,40", "f2": "", "f3": "", "pcv": "9,5", "durata": "24 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "BIMESTRALE", "switch_voltura": "NO", "subentro": "", "note_raw": ""}' },
      { provider: 'A2A', name: 'NOI 2', canone: '0,105 +0,020', vincolo: '', scadenza: '', type: 'consumer', note: '', details: '{"fornitura": "LUCE", "tipologia": "CONSUMER", "tipo_offerta": "", "f1": "0,105 +0,020", "f2": "", "f3": "", "pcv": "9,5", "durata": "", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "BIMESTRALE", "switch_voltura": "", "subentro": "", "note_raw": ""}' },
      { provider: 'A2A', name: 'SMART LUCE BUSINESS', canone: 'PUN+0,20', vincolo: '12 MESI', scadenza: '', type: 'business', note: '', details: '{"fornitura": "LUCE", "tipologia": "BUSINESS", "tipo_offerta": "", "f1": "PUN+0,20", "f2": "", "f3": "", "pcv": "15", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "BIMESTRALE", "switch_voltura": "", "subentro": "", "note_raw": ""}' },
      { provider: 'A2A', name: 'ESCLUSIVA A2A BUSINESS', canone: 'FISSO 0,152', vincolo: '12 MESI', scadenza: '', type: 'business', note: '', details: '{"fornitura": "LUCE", "tipologia": "BUSINESS", "tipo_offerta": "", "f1": "FISSO 0,152", "f2": "", "f3": "", "pcv": "15", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "BIMESTRALE", "switch_voltura": "", "subentro": "", "note_raw": ""}' },
      { provider: 'A2A', name: 'PREZZO SICURO BUSINESS', canone: 'FISSO 0,147', vincolo: '24 MESI', scadenza: '', type: 'business', note: '', details: '{"fornitura": "LUCE", "tipologia": "BUSINESS", "tipo_offerta": "", "f1": "FISSO 0,147", "f2": "", "f3": "", "pcv": "15", "durata": "24 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "BIMESTRALE", "switch_voltura": "", "subentro": "", "note_raw": ""}' },
      { provider: 'A2A', name: 'SMART BUSINESS', canone: 'PSV+,011', vincolo: '12 MESI', scadenza: '', type: 'business', note: '', details: '{"fornitura": "GAS", "tipologia": "BUSINESS", "tipo_offerta": "", "f1": "PSV+,011", "f2": "", "f3": "", "pcv": "15", "durata": "12 MESI", "scadenza_offerta": "", "pagamento": "RID/BOLLETTINO", "cauzione": "", "fatturazione": "BIMESTRALE", "switch_voltura": "", "subentro": "", "note_raw": ""}' }    ];

    for (const offer of energyOffers) {
      await queryRunner.query(
        `INSERT INTO offers (id, category, provider, name, canone, attivazione, vincolo, note, disattivazione, type, scadenza, is_active, sort_order, details)
         VALUES (uuid_generate_v4(), 'ENERGY', $1, $2, $3, NULL, $4, $5, NULL, $6, $7, true, 0, $8)`,
        [offer.provider, offer.name, offer.canone, offer.vincolo, offer.note, offer.type, offer.scadenza, offer.details],
      );
    }

    // === 4. Inserisci offerte MOBILE con details (idempotente) ===
    const mobileOffers = [
      { provider: 'ALTRO', name: 'POWER FAMIGLIA IRON - ODULG', canone: '€4,99', attivazione: '€6,99', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "VIRTUALE- NO ILIAD/POSTE", "attivazione": "€6,99", "minutes": "ILLIMITATE", "sms": "200", "gb": "1GB", "has_5g": false, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'ALTRO', name: 'SUPREME GPRO - ODU22', canone: '€5,99', attivazione: '€6,99', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "VIRTUALE+ILIAD - NO POSTE", "attivazione": "€6,99", "minutes": "ILLIMITATE", "sms": "200", "gb": "150GB", "has_5g": false, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'ALTRO', name: 'POWER IRON - ODUNE', canone: '€6,99', attivazione: '€6,99', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "VIRTUALE+ILIAD +  POSTE", "attivazione": "€6,99", "minutes": "ILLIMITATE", "sms": "200", "gb": "200GB", "has_5g": false, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'ALTRO', name: 'POWER SPECIAL NEW EASY 5G - ODUP4 (SOLO RIC AUTO)', canone: '€9,00', attivazione: '€6,99', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "VIRTUALE+ILIAD - NO POSTE", "attivazione": "€6,99", "minutes": "ILLIMITATE", "sms": "200", "gb": "300GB", "has_5g": true, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'TIM', name: 'TIM YOUNG FULL - ODUM8', canone: '€7,99', attivazione: '€6,99', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "UNDER 30 VIRTUALE+ILIAD", "attivazione": "€6,99", "minutes": "ILLIMITATE", "sms": "200", "gb": "ILLIMITATI", "has_5g": false, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'TIM', name: 'TIM YOUNG FULL+APPLE MUSIC - MD01F', canone: '€9,99', attivazione: '€6,99', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "UNDER 30 VIRTUALE+ILIAD", "attivazione": "€6,99", "minutes": "ILLIMITATE", "sms": "200", "gb": "ILLIMITATI", "has_5g": false, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'TIM', name: 'TIM YOUNG FULL+SMARTPHONE - ODUM8', canone: '€9,99', attivazione: '€6,99', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "UNDER 30 VIRTUALE+ILIAD", "attivazione": "€6,99", "minutes": "ILLIMITATE", "sms": "200", "gb": "ILLIMITATI", "has_5g": false, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'TIM', name: 'TIM YOUNG - ODUM2', canone: '€9,99', attivazione: '€6,99', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "UNDER 30 TUTTI GLI OPERATORI", "attivazione": "€6,99", "minutes": "ILLIMITATE", "sms": "200", "gb": "200GB (+50 RID)", "has_5g": false, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'TIM', name: 'TIM YOUNG CARTA GIOVANI - ODUM4', canone: '€9,99', attivazione: '€6,99', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "UNDER 30 TUTTI GLI OPERATORI", "attivazione": "€6,99", "minutes": "ILLIMITATE", "sms": "200", "gb": "300GB", "has_5g": true, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'TIM', name: 'TIM POWER SUPREME LIMITED', canone: '€7,99', attivazione: '6,99', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "VODAFONE (Promo a codice)", "attivazione": "6,99", "minutes": "ILLIMITATE", "sms": "ILL.", "gb": "250GB", "has_5g": true, "abroad_gb": "20GB", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'TIM', name: 'TIM ONE GO', canone: '€9,99', attivazione: '6,99', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "VODAFONE", "attivazione": "6,99", "minutes": "ILLIMITATE", "sms": "200", "gb": "100GB", "has_5g": false, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'TIM', name: 'TIM STEEL NEW GPRO', canone: '€7,99', attivazione: '6,99', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "WIND/VERY (Promo a codice)", "attivazione": "6,99", "minutes": "ILLIMITATE", "sms": "ILL.", "gb": "100GB", "has_5g": true, "abroad_gb": "20GB", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'TIM', name: 'TIM TITANIUM ORANGE 5G - ODV6E', canone: '€10,99', attivazione: '€6,99', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "WIND/VERY", "attivazione": "€6,99", "minutes": "ILLIMITATE", "sms": "200", "gb": "150GB", "has_5g": true, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'TIM', name: 'TIM JET 5G - ODV7B', canone: '€9,99', attivazione: '€6,99', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "SOLO NUOVO NUMERO", "attivazione": "€6,99", "minutes": "ILLIMITATE", "sms": "200", "gb": "100GB", "has_5g": true, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'TIM', name: 'TIM MOBILE - ( CREDITO RESIDUO ODV2W - RID ODV19)', canone: '€12,99', attivazione: '€9,99', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI/NUOVO NUMERO/CB", "attivazione": "€9,99", "minutes": "ILLIMITATE", "sms": "200", "gb": "50GB (+50 RID)", "has_5g": true, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'TIM', name: 'TIM MOBILE E MUSIC (CON APPLE MUSIC) - MD01B', canone: '€14,99', attivazione: '€9,99', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI/NUOVO NUMERO/CB", "attivazione": "€9,99", "minutes": "ILLIMITATE", "sms": "200", "gb": "200GB", "has_5g": true, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'TIM', name: 'TIM MOBILE MUSIC E TV (CON APPLE MUSIC+TIM VISION S) - MD01E', canone: '€19,99', attivazione: '€9,99', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI/NUOVO NUMERO/CB", "attivazione": "€9,99", "minutes": "ILLIMITATE", "sms": "200", "gb": "300GB", "has_5g": true, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'TIM', name: 'TIM MOBILE MUSIC E TV UNLIMITED (CON APPLE MUSIC E TIM VISION L)', canone: '€25,99', attivazione: '€9,99', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI/NUOVO NUMERO/CB", "attivazione": "€9,99", "minutes": "ILLIMITATE", "sms": "200", "gb": "ILLIMITATI", "has_5g": true, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'TIM', name: 'HOME CONNECT 24 MESI', canone: '€49,00', attivazione: '0', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "NUOVO NUMERO", "attivazione": "0", "minutes": "50", "sms": "100", "gb": "500 MEGA", "has_5g": false, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'TIM', name: 'HOME CONNECT', canone: '€4,99', attivazione: '5€', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "NUOVO NUMERO", "attivazione": "5€", "minutes": "50", "sms": "100", "gb": "500 MEGA", "has_5g": false, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'SKY MOBILE', name: 'MOBILE START', canone: '€9,95', attivazione: '10€', vincolo: 'NO', type: 'consumer', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI", "attivazione": "10€", "minutes": "ILLIMITATE", "sms": "200", "gb": "150GB", "has_5g": true, "abroad_gb": "32GB (17GB SVIZZERA/EXTRA UE)", "postepay": true, "vincolo": "NO", "exit_costs": "0€", "note_raw": ""}' },
      { provider: 'SKY MOBILE', name: 'MOBILE PRO', canone: '€11,95', attivazione: '10€', vincolo: 'NO', type: 'consumer', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI", "attivazione": "10€", "minutes": "ILLIMITATE", "sms": "200", "gb": "250GB", "has_5g": true, "abroad_gb": "45GB (20GB SVIZZERA/EXTRA UE)", "postepay": true, "vincolo": "NO", "exit_costs": "0€", "note_raw": ""}' },
      { provider: 'SKY MOBILE', name: 'MOBILE POWER', canone: '€14,95', attivazione: '10€', vincolo: 'NO', type: 'consumer', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI", "attivazione": "10€", "minutes": "ILLIMITATE", "sms": "200", "gb": "400GB", "has_5g": true, "abroad_gb": "65GB (40GB SVIZZERA/EXTRA UE)", "postepay": true, "vincolo": "NO", "exit_costs": "0€", "note_raw": ""}' },
      { provider: 'SKY MOBILE', name: 'MOBILE ULTRA', canone: '€19,95', attivazione: '10€', vincolo: 'NO', type: 'consumer', note: '1000 MIN VERSO UE/USA+ALTRI PAESI ASSICURAZIONE QUIXA CANE E GATTO', details: '{"provenienza": "TUTTI GLI OPERATORI", "attivazione": "10€", "minutes": "ILLIMITATE", "sms": "200", "gb": "ILLIMITATI", "has_5g": true, "abroad_gb": "GB ILLIMITATI UE (5GB EXTRA UE)", "postepay": true, "vincolo": "NO", "exit_costs": "0€", "note_raw": "1000 MIN VERSO UE/USA+ALTRI PAESI ASSICURAZIONE QUIXA CANE E GATTO"}' },
      { provider: 'ILIAD', name: 'GO XXS', canone: '€4,99', attivazione: '0', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "ILIAD/OPTIMA/COOP", "attivazione": "0", "minutes": "ILLIMITATE", "sms": "", "gb": "200GB", "has_5g": true, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'HO', name: 'DOMOTICA', canone: '€1,99', attivazione: '10', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI", "attivazione": "10", "minutes": "ILLIMITATI", "sms": "100", "gb": "200MB", "has_5g": false, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'HO', name: 'VOCE', canone: '€4,99', attivazione: '10', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI", "attivazione": "10", "minutes": "ILLIMITATI", "sms": "ILL", "gb": "40MB", "has_5g": false, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'HO', name: 'TOP 170', canone: '€7,99', attivazione: '10', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI", "attivazione": "10", "minutes": "ILLIMITATI", "sms": "ILL", "gb": "170GB", "has_5g": false, "abroad_gb": "17GB UE", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'HO', name: 'TOP 200', canone: '€9,99', attivazione: '10', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI", "attivazione": "10", "minutes": "ILLIMITATI", "sms": "ILL", "gb": "200GB", "has_5g": false, "abroad_gb": "25GB UE", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'HO', name: 'TOP 300', canone: '€11,99', attivazione: '10', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI", "attivazione": "10", "minutes": "ILLIMITATI", "sms": "ILL", "gb": "300GB", "has_5g": false, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'HO', name: 'BUSINESS 180 (SOLO DATI)', canone: '€9,99', attivazione: '10', vincolo: '', type: 'business', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI", "attivazione": "10", "minutes": "//", "sms": "ILL", "gb": "180GB", "has_5g": false, "abroad_gb": "19GB UE+5GB EXTRA UE", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'HO', name: 'BUSINESS GIGA 300', canone: '€11,99', attivazione: '10', vincolo: '', type: 'business', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI", "attivazione": "10", "minutes": "ILLIMITATI", "sms": "ILL", "gb": "300GB", "has_5g": false, "abroad_gb": "22GB UE+5GB EXTRA UE", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'OPTIMA', name: 'SUPER MOBILE SMART', canone: '€4,99', attivazione: '20€', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI", "attivazione": "20€", "minutes": "ILLIMITATE", "sms": "200", "gb": "100", "has_5g": false, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'OPTIMA', name: 'SUPER MOBILE 5G', canone: '€6,99', attivazione: '20€', vincolo: '', type: 'consumer', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI", "attivazione": "20€", "minutes": "ILLIMITATE", "sms": "200", "gb": "250", "has_5g": true, "abroad_gb": "", "postepay": false, "vincolo": "", "exit_costs": "", "note_raw": ""}' },
      { provider: 'SKY MOBILE', name: 'MOBILE START', canone: '€9,95', attivazione: '10€', vincolo: 'NO', type: 'consumer', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI", "attivazione": "10€", "minutes": "ILLIMITATE", "sms": "200", "gb": "150GB", "has_5g": true, "abroad_gb": "32GB (17GB SVIZZERA/EXTRA UE)", "postepay": false, "vincolo": "NO", "exit_costs": "0€", "note_raw": ""}' },
      { provider: 'SKY MOBILE', name: 'MOBILE PRO', canone: '€11,95', attivazione: '10€', vincolo: 'NO', type: 'consumer', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI", "attivazione": "10€", "minutes": "ILLIMITATE", "sms": "200", "gb": "250GB", "has_5g": true, "abroad_gb": "45GB (20GB SVIZZERA/EXTRA UE)", "postepay": false, "vincolo": "NO", "exit_costs": "0€", "note_raw": ""}' },
      { provider: 'SKY MOBILE', name: 'MOBILE POWER', canone: '€14,95', attivazione: '10€', vincolo: 'NO', type: 'consumer', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI", "attivazione": "10€", "minutes": "ILLIMITATE", "sms": "200", "gb": "400GB", "has_5g": true, "abroad_gb": "65GB (40GB SVIZZERA/EXTRA UE)", "postepay": false, "vincolo": "NO", "exit_costs": "0€", "note_raw": ""}' },
      { provider: 'SKY MOBILE', name: 'MOBILE ULTRA', canone: '€19,95', attivazione: '10€', vincolo: 'NO', type: 'consumer', note: '', details: '{"provenienza": "TUTTI GLI OPERATORI", "attivazione": "10€", "minutes": "ILLIMITATE", "sms": "200", "gb": "ILLIMITATI", "has_5g": true, "abroad_gb": "GB ILLIMITATI UE (5GB EXTRA UE)", "postepay": false, "vincolo": "NO", "exit_costs": "0€", "note_raw": ""}' }    ];

    for (const offer of mobileOffers) {
      const exists = await queryRunner.query(
        `SELECT id FROM offers WHERE name = $1 AND provider = $2 AND category = 'MOBILE'`,
        [offer.name, offer.provider],
      );
      if (exists.length === 0) {
        await queryRunner.query(
          `INSERT INTO offers (id, category, provider, name, canone, attivazione, vincolo, note, disattivazione, type, scadenza, is_active, sort_order, details)
           VALUES (uuid_generate_v4(), 'MOBILE', $1, $2, $3, $4, $5, $6, NULL, $7, NULL, true, 0, $8)`,
          [offer.provider, offer.name, offer.canone, offer.attivazione, offer.vincolo, offer.note, offer.type, offer.details],
        );
      }
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Elimina offerte Energy e Mobile importate da questa migration
    await queryRunner.query(
      `DELETE FROM offers WHERE category = 'ENERGY' AND provider IN ('OPTIMA','IREN','ITALIA POWER','WINDTRE','ACEA','FASTWEB','A2A')`
    );
    await queryRunner.query(
      `DELETE FROM offers WHERE category = 'MOBILE' AND provider IN ('TIM','ILIAD','SKY MOBILE','OPTIMA','HO','ALTRO')`
    );
    // NOTA: non eliminiamo la colonna details per non perdere dati di altre offerte
  }
}
